version: '3'

services:
  php:
    image: leroymerlinbr/php
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mongo:4.0
    command: mongod --smallfiles
    volumes:
      - db:/data/db
      - .:/var/www/html

  mkdocs:
    image: polinux/mkdocs
    volumes:
      - .:/workdir/mkdocs

volumes:
  db:
    driver: local
