name: Continuous Integration
on:
  - pull_request
  - push
jobs:
  testing:
    name: Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php:
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
        mongo:
          - "3.6"
          - "4.0"
          - "4.2"
          - "4.4"
          - "5.0"
          - "6.0"
          - "7.0"
    services:
      mongodb:
        image: mongo:${{ matrix.mongo }}
        ports:
          - "27017:27017"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mongodb-mongodb/mongo-php-driver@1.17.0
          tools: cs2pr

      - name: Composer
        uses: ramsey/composer-install@v2

      - name: Run phpcs
        run: vendor/bin/phpcs -q --report=checkstyle | cs2pr

      - name: Running tests
        run: vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=./coverage/clover.xml

      - name: Report coverage
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage/clover.xml
